### ISSUE TITLE
Buttons to toggle list type (ul/ol) missing

### ISSUE THREAD

**Issue by igregson** [getkirby/blocks#49]
![image](https://user-images.githubusercontent.com/2054975/99107839-53bd3700-259b-11eb-9620-140e21d827d5.png)

From seeing screenshots in the Discord channel it seems there should be list-type toggle buttons here.

Also, I can't find any way to start with a numbered list. Typing `1.` creates an unordered list. Can create a separate issue for this if needed.

**Comment by johannschopplich** [comment]
Since Bastian is constantly tweaking the UI and listening to ideas from the community, some UI elements change for alpha versions of the Blocks plugin. You can read all about in the Discord. It's quite a lot, I know. 😉 Numbered lists can be achieved by:

![mixed-lists 2020-11-14 12_19_55](https://user-images.githubusercontent.com/27850750/99145955-b8e45b80-2673-11eb-9948-9ddbb43ff9f7.gif)

(Video originally created by Bastian.)
